### ISSUE TITLE
感谢你的工作，它正是我需要的，但是我出现了如下错误，请求你的帮助

### ISSUE THREAD

**Issue by Baobaon** [lyq0724/Clip#1]
Traceback (most recent call last):
  File "/data/server03/Zhaozikai/Clip/train.py", line 170, in <module>
    model   = CLIP(**config)
  File "/data/server03/Zhaozikai/Clip/nets/clip.py", line 57, in __init__
    self.tokenizer          = BertTokenizer.from_pretrained(kwargs['huggingface_model_name'])
  File "/home/server03/anaconda3/envs/Zhao_project926/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2192, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by Baobaon** [comment]
我解决了上面的问题
我在flickr8k数据集上训练的结果如下：
![81e9a28147f29864cdfea37918cddee8](https://github.com/user-attachments/assets/fa45d360-089a-4fc6-8075-d43bd1d5a324)
为什么训练的效果还不如不训练？
